name: "bruh - Bicep Resource Update Helper"
author: "Christos Galanopoulos"
description: "Scan and update Bicep files with outdated API versions"
branding:
  icon: alert-circle
  color: gray-dark
inputs:
  # general
  command:
    description: "The command to run (scan or update)"
    required: true
  path:
    description: "The path to the bicep file or directory"
    required: false
  include-preview:
    description: "Include preview API versions"
    required: false
    default: "false"
  summary:
    description: "Show action summary"
    required: false
    default: "false"

  # scan specific
  outdated:
    description: "Only show outdated resources (only for scan command)"
    required: false
    default: "false"
  output:
    description: "The output format (normal | table | markdown) (only for scan command)"
    required: false
    default: "normal"

  # update specific
  in-place:
    description: "Overwrite the input file(s) (only for update command)"
    required: false
    default: "true"
  silent:
    description: "Silent output (only for update command)"
    required: false
    default: "false"

outputs:
  result:
    description: "The complete result from the bruh command being run"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
    - --path=${{ inputs.path }}
    - --include-preview=${{ inputs.include-preview }}
    - --outdated=${{ inputs.outdated }}
    - --output=${{ inputs.output }}
    - --in-place=${{ inputs.in-place }}
    - --silent=${{ inputs.silent }}
    - --summary=${{ inputs.summary }}
