version: "3"

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -l
    silent: true

  # Lint
  lint:fmt:
    desc: Format code
    aliases:
      - "fmt"
      - "format"
    cmds:
      - gofmt -s -w -l .
    silent: true

  lint:vet:
    desc: Vet code
    aliases:
      - "vet"
    cmds:
      - go vet ./internal/*
      - go vet ./cmd/*
    silent: true

  lint:revive:
    desc: Lint code
    aliases:
      - "rv"
      - "revive"
    cmds:
      - revive -config revive.toml -formatter friendly ./internal/*
      - revive -config revive.toml -formatter friendly ./cmd/*
    silent: true

  lint:all:
    desc: Run all lint tasks
    cmds:
      - task lint:fmt
      - task lint:vet
      - task lint:revive
    silent: true

  # Test
  test:internal:parse:
    desc: Run tests for parse package
    aliases:
      - "test:parse"
    dir: ./internal/parse
    cmds:
      - go test -v
      - go test -cover
    silent: true

  test:internal:azapiversions:
    desc: Run tests for azapiversions package
    aliases:
      - "test:azapiversions"
      - "test:azapi"
    dir: ./internal/azapiversions
    cmds:
      - go test -v
      - go test -cover
    silent: true

  test:internal:all:
    desc: Run all tests for all packages
    aliases:
      - "test:all"
    cmds:
      - printf "---------- parse ------------------\n\n" && task test:internal:parse && printf "\n\n"
      - printf "---------- azapiversions -----------\n\n" && task test:internal:azapiversions && printf "\n\n"
    silent: true

  # Build
  build:bruh:
    desc: Build bruh
    aliases:
      - "build"
    dir: ./cmd/bruh
    cmds:
      - go build -o bruh ./main.go
    silent: true

  # Run
  run:bruh:
    desc: Run bruh
    aliases:
      - "run"
    deps:
      - build:bruh
    cmds:
      - ./cmd/bruh/bruh
    silent: true

  # All
  all:
    desc: Run all tasks in order
    aliases:
      - "all"
    cmds:
      - printf "\n---------- LINT -----------\n\n" && task lint:all && printf "\n\n"
      - printf "---------- TEST -----------\n\n" && task test:internal:all && printf "\n\n"
      - printf "---------- BUILD ----------\n\n" && task build:bruh && printf "\n\n"
      - printf "---------- RUN ------------\n\n" && task run:bruh && printf "\n\n"
      - printf "---------- CLEAN ----------\n\n" && task clean && printf "\n\n"
    silent: true

  # Clean
  clean:
    desc: Clean binaries
    aliases:
      - "clean"
    cmds:
      - rm ./cmd/bruh/bruh
    silent: true
