version: "3"

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -l
    silent: true

  # Lint
  lint:fmt:
    desc: Format code
    aliases:
      - "fmt"
      - "format"
    cmds:
      - gofmt -s -w -l .
    silent: true

  lint:vet:
    desc: Vet code
    aliases:
      - "vet"
    cmds:
      - go vet ./internal/*
      - go vet ./cmd/*
    silent: true

  lint:revive:
    desc: Lint code
    aliases:
      - "rv"
      - "revive"
    cmds:
      - revive -config revive.toml -formatter friendly ./internal/*
      - revive -config revive.toml -formatter friendly ./cmd/*
    silent: true

  lint:all:
    desc: Run all lint tasks
    cmds:
      - task lint:fmt
      - task lint:vet
      - task lint:revive
    silent: true

  # Test
  test:internal:bicep:
    desc: Run tests for bicep package
    aliases:
      - "test:bicep"
    dir: ./internal/bicep
    cmds:
      - go test -v
    silent: true

  test:internal:bicep:parse:
    desc: Run tests for bicep package's parse methods
    aliases:
      - "test:update"
      - "test:bicep:update"
    dir: ./internal/bicep
    cmds:
      - go test -v -run "TestParse"
    silent: true

  test:internal:bicep:update:
    desc: Run tests for bicep package's update methods
    aliases:
      - "test:parse"
      - "test:bicep:parse"
    dir: ./internal/bicep
    cmds:
      - go test -v -run "TestUpdate"
    silent: true

  test:internal:bicep:parse-update:
    desc: Run tests for bicep package's  parse and update methods combined
    aliases:
      - "test:pu"
      - "test:parse-update"
      - "test:bicep:parse-update"
    dir: ./internal/bicep
    cmds:
      - go test -v -run "TestParseUpdate"
    silent: true

  test:internal:apiversions:
    desc: Run tests for apiversions package
    aliases:
      - "test:apiversions"
      - "test:azapi"
    dir: ./internal/apiversions
    cmds:
      - go test -v
    silent: true

  test:internal:coverage:
    desc: Generate coverage report for all packages
    aliases:
      - "test:coverage"
      - "test:cov"
    dir: ./internal
    cmds:
      - go test -cover ./bicep
      - go test -cover ./apiversions
    silent: true

  test:internal:all:
    desc: Run all tests for all packages
    aliases:
      - "test:all"
    cmds:
      - printf "---------- bicep ---------------------------------\n\n" && task test:internal:bicep && printf "\n\n"
      - printf "---------- apiversions ---------------------------\n\n" && task test:internal:apiversions && printf "\n\n"
    silent: true

  # Build
  build:bruh:
    desc: Build bruh
    aliases:
      - "build"
    dir: ./cmd/bruh
    cmds:
      - go build -o bruh ./main.go
    silent: true

  # Run
  run:bruh:
    desc: Run bruh
    aliases:
      - "run"
    deps:
      - build:bruh
    cmds:
      - ./cmd/bruh/bruh
    silent: true

  # All
  all:
    desc: Run all tasks in order
    aliases:
      - "all"
    cmds:
      - printf "---------- LINT ----------------------------------\n\n" && task lint:all
      - printf "---------- TEST ----------------------------------\n\n" && task test:internal:all
      - printf "---------- COVERAGE ------------------------------\n\n" && task test:coverage && printf "\n"
      - printf "---------- BUILD ---------------------------------\n\n" && task build:bruh
      - printf "---------- RUN -----------------------------------\n\n" && task run:bruh
      - printf "---------- CLEAN ---------------------------------\n\n" && task clean
    silent: true

  # Clean
  clean:
    desc: Clean binaries
    aliases:
      - "clean"
    cmds:
      - rm ./cmd/bruh/bruh
    silent: true
