version: "3"

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -l
    silent: true

  # Lint
  lint:fmt:
    desc: Format code
    aliases:
      - "fmt"
      - "format"
    cmds:
      - gofmt -s -w -l .
    silent: true

  lint:vet:
    desc: Vet code
    aliases:
      - "vet"
    cmds:
      - go vet ./pkg/*
      - go vet ./cmd/*
    silent: true

  lint:revive:
    desc: Lint code
    aliases:
      - "rv"
      - "revive"
    cmds:
      - revive -config revive.toml -formatter friendly ./pkg/*
      - revive -config revive.toml -formatter friendly ./cmd/*
    silent: true

  lint:all:
    desc: Run all lint tasks
    cmds:
      - task lint:fmt
      - task lint:vet
      - task lint:revive
    silent: true

  # Test
  test:pkg:parser:
    desc: Run tests for parser package
    aliases:
      - "test:parser"
    dir: ./pkg/parser
    cmds:
      - go test -v
      - go test -cover
    silent: true

  test:pkg:all:
    desc: Run all tests for all packages
    aliases:
      - "test:all"
    cmds:
      - task test:pkg:parser
    silent: true

  # Build
  build:bruh:
    desc: Build bruh
    aliases:
      - "build"
    dir: ./cmd/bruh
    cmds:
      - go build -o bruh ./main.go
    silent: true

  # Run
  run:bruh:
    desc: Run bruh
    aliases:
      - "run"
    deps:
      - build:bruh
    cmds:
      - ./cmd/bruh/bruh
    silent: true

  # Complete
  complete:bruh:
    desc: Complete bruh
    aliases:
      - "complete"
    cmds:
      - printf "\n---------- LINT -----------\n\n" && task lint:all && printf "\n\n"
      - printf "---------- TEST -----------\n\n" && task test:pkg:all && printf "\n\n"
      - printf "---------- BUILD ----------\n\n" && task build:bruh && printf "\n\n"
      - printf "---------- RUN ------------\n\n" && task run:bruh && printf "\n\n"
      - printf "---------- CLEAN ----------\n\n" && task clean && printf "\n\n"
    silent: true

  # Clean
  clean:
    desc: Clean binaries
    aliases:
      - "clean"
    cmds:
      - rm ./cmd/bruh/bruh
    silent: true
