name: action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          command: scan
          path: ./internal/bicep/testdata
          include-preview: true
          output: table
          outdated: false
          in-place: true
          silent: false
