name: action

on:
  workflow_dispatch:

jobs:
  test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          command: scan
          path: ./internal/bicep/testdata
          include-preview: true
          output: normal
          outdated: false

      - uses: ./
        with:
          command: scan
          path: ./internal/bicep/testdata
          include-preview: true
          output: normal
          outdated: true

      - uses: ./
        with:
          command: scan
          path: ./internal/bicep/testdata
          include-preview: true
          output: table
          outdated: false

      - uses: ./
        with:
          command: scan
          path: ./internal/bicep/testdata
          include-preview: true
          output: table
          outdated: true  

  test-update:
    runs-on: ubuntu-latest
    needs: test-scan
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          command: update
          path: ./internal/bicep/testdata
          include-preview: true
          in-place: false
          silent: false

      - uses: ./
        with:
          command: update
          path: ./internal/bicep/testdata
          include-preview: true
          in-place: false
          silent: true

      - uses: ./
        with:
          command: update
          path: ./internal/bicep/testdata
          include-preview: true
          in-place: true
          silent: false

      - uses: ./
        with:
          command: update
          path: ./internal/bicep/testdata
          include-preview: true
          in-place: true
          silent: true
  
  test-both:
    runs-on: ubuntu-latest
    needs: test-update
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          command: scan
          path: ./internal/bicep/testdata
          include-preview: true
          output: table
          outdated: false

      - uses: ./
        with:
          command: update
          path: ./internal/bicep/testdata
          include-preview: true
          in-place: true

      - uses: ./
        with:
          command: scan
          path: ./internal/bicep/testdata
          include-preview: true
          output: normal
          outdated: true
  
  test-error:
    runs-on: ubuntu-latest
    needs: test-both
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          command: random
        continue-on-error: true
      
      - uses: ./
        with:
          command: scan
          include-preview: random
        continue-on-error: true

      - uses: ./
        with:
          command: scan
          outdated: random
        continue-on-error: true

      - uses: ./
        with:
          command: scan
          output: random
        continue-on-error: true

      - uses: ./
        with:
          command: update
          in-place: random
        continue-on-error: true

      - uses: ./
        with:
          command: update
          silent: random
        continue-on-error: true