name: ci
run-name: ${{ github.workflow }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.0'
    
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Go tools
      run: task install:tools
    
    - name: Lint
      run: task lint:all
    
    - name: Test
      run: task test:all
    
    - name: Code Coverage
      run: task coverage
    
    - name: Security
      run: task security:all
