name: ci
run-name: ${{ github.workflow }}

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - 'Formula/*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'Formula/*'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ci:
    name: ci
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Go tools
      run: task setup
    
    - name: Lint
      run: task lint
    
    - name: Test
      run: task test
    
    - name: Code Coverage
      run: task coverage
    
    - name: Security
      run: task security
